### ISSUE TITLE
[Task]: バックエンドとフロントエンドの接続

### ISSUE THREAD

**Issue by Shiluco** [GreenTeaProgrammers/difflog2#46]
### Who do?

未定

### As Is

developブランチでgoサーバーを起動してもフロントエンドと接続できない

### To Be

通信できるようにする

### Action

500番エラーが出てるからそれを無くす。

### content Check

- [X] I agree to follow this project's Code of Conduct

**Comment by Hosi121** [comment]
原因
それぞれのserviceでハードコードされているので、立てたサーバとアドレスを対応付ける必要がある．
ここで、apiオブジェクトは抽象化する必要がある
